#pragma once
namespace mmvr {
// Read-only tutorial rows use the existing scrolling menu, never gameplay actions.
struct ControlTutorialEntry { const char* title; const char* first; const char* second; };
inline constexpr ControlTutorialEntry ControlTutorial[] = {
    { "Reading this guide", "Default Touch names below; Controls shows your current bindings.", "Scroll with the left stick. X collapses; B closes settings." },
    { "Your dominant hand", "Hands > Dominant hand swaps sword, items, wheel and shield.", "It does not swap menu sticks or physical buttons; Controls can rebind actions." },
    { "Walk, turn and run", "Left stick walks; right stick turns. Left stick click recenters.", "Alternate your arms while walking for a 20% ground-speed boost by default; adjust it in Forms." },
    { "Buttons and targeting", "A interacts/confirms or performs the displayed native action.", "Y toggles targeting; Combat offers hold targeting and optional target camera orbit." },
    { "Third-person / theater controls", "Left trigger shields; hold left grip to lock on. Right trigger uses the selected item or mask.", "Combat offers separate third-person toggle targeting; transformations use the theater screen." },
    { "Original third-person controls", "Enable Original third-person VR controls to use right-stick C-buttons instead of the wheel.", "A regular gamepad keeps its native 2Ship controls and C-button HUD in third-person/theater." },
    { "Sword / form action / fairy", "B draws or stows equipment; hold B for supported form attacks.", "X answers the fairy. Controls offers optional double-tap sword draw." },
    { "Pause and settings", "Left menu button opens inventory; triggers change its pages.", "Right stick click opens VR settings, including on the title screen." },
    { "Assign your item wheel", "Browse inventory with the left stick and highlight an owned item.", "Push the right stick toward a wheel slot, then center it to assign." },
    { "Select an item", "Hold dominant grip; move that hand onto a wheel slot and release.", "Items > Bottle and mask tuning offers instant mask/instrument readiness; other items use trigger." },
    { "Wheel options", "Items supports 4-8 slots; extra slots occupy the four corners.", "Release away from a slot to clear selection when gameplay permits." },
    { "Sword and Deku stick", "Swing deliberately through targets; stationary touching cannot hit.", "Sticks retain burning/breaking. Native weapon damage still applies." },
    { "Spin slash", "Hold sword trigger to charge (2 seconds); release with the blade held out.", "Fast physical turns use great spin when unlocked and magic is available; Combat has the toggle." },
    { "Physical spin and sword beam", "Turn physically with the sword extended for a regular spin.", "Fierce Deity: hold trigger and swing; beam follows headset aim." },
    { "Spin comfort and holster", "Combat can disable the triggered 360-degree camera turn.", "Empty hand/item slot: grip behind your shoulder to equip the sword; release freely." },
    { "Blocking", "Hold offhand grip; put your shield between you and the attack.", "Combat can keep Human Link's shield out with his sword. Other forms keep their usual controls." },
    { "Bow and elemental arrows", "Select the bow or arrow type; the bow is held in your offhand.", "Hold dominant trigger near the string, pull back, release to shoot." },
    { "Hookshot", "Point the equipped hookshot and press the dominant trigger.", "Items offers optional head aim for bow/hookshot; controller aim is the default." },
    { "Bombs, nuts and powder kegs", "Select, hold the dominant trigger to ready, then release to throw.", "Move your hand to throw; release gently to drop. Form rules apply." },
    { "Bombchus", "Hold trigger to ready one; release to place it.", "The placement reticle follows your headset direction." },
    { "Picking up and throwing", "Reach a permitted object with either free hand and press trigger.", "Hold to carry; release to drop or throw. Cuccos allow native gliding." },
    { "Physical push and pull", "Touch a pushable with both palms and hold both triggers.", "Push/pull your hands or use the stick. Release either trigger to stop." },
    { "Bottles", "Sweep an empty bottle through catchable creatures or water.", "Trigger releases/pours contents; potions and milk play drinking." },
    { "Putting on masks", "Normally hold trigger, bring the mask to your face, then release to wear.", "Instant readiness: select, bring to face to wear; trigger dismisses the held mask." },
    { "Removing and replacing masks", "At your face, press either free-hand trigger, pull away and release.", "Story-locked forms cannot be removed; permitted masks can replace." },
    { "Offering quest items", "Select the item and trigger near the NPC, or during their request.", "Native story/item conditions apply; not everyone accepts offers." },
    { "Other items and viewing tools", "Select an item and use its trigger; follow native action prompts.", "Pictograph aim follows your head. Lens of Truth still uses magic." },
    { "Deku form", "Hold B to charge a bubble; release to fire along headset aim.", "A at flowers follows the burrow/launch prompt; offhand grip shields." },
    { "Deku physical spin", "Turn quickly in place to trigger the native Deku spin attack.", "The usual ground and action restrictions apply; this does not burrow." },
    { "Goron form", "With hands free, tap B to ready fists; swing deliberately to punch.", "Offhand grip curls; follow native roll/pound prompts. B jumps rolling." },
    { "Zora form", "Swing deliberately to strike with fins. Hold B to aim; release to throw.", "Aim follows your head. Throw targeting clears when both fins return." },
    { "Swimming and riding", "Swim and Zora dash aim follow your head; use native swim prompts.", "On Epona, use the movement stick and native A speed/action prompt." },
    { "Physical climbing", "At a climbable ladder/vine, hold trigger and pull your hand down.", "Alternate hands; release to let go. Items > Climbing has both modes." },
    { "Ocarina and form instruments", "Select and trigger, or enable instant readiness. Either stick plays C notes.", "A/X plays the fifth note; B/Y cancels. Instant readiness also allows trigger to cancel free play." },
    { "Song choices and dialogue", "For a song Yes/No choice, use either stick; A confirms.", "For other dialogue, navigate the displayed choices and press A." },
    { "Save states", "System > Save states restores progress, settings and saved pack selection.", "Pack changes restart safely. Compatible layouts and original pack files are required." },
    { "2Ship options", "2Ship contains Audio, Gameplay, Cheats, Difficulty and Randomizer.", "Left stick selects; A opens; B goes back. Triggers change VR tabs." },
    { "2Ship pointer and keyboard", "Text field: A opens keyboard; left stick selects keys; A types.", "Right stick also points. Enter finishes typing. Hover tabs to read full names." },
    { "Mods and texture packs", "System > Mod library: refresh, expand folders and tick each pack.", "Restart to load changes. States restore pack choices; keep required pack versions." },
    { "Transfer normal saves", "At file selection, use 2Ship > Save files to import or export a JSON save.", "PCVR and Quest share normal saves, including owl progress. States are separate." },
    { "Playing as Kafei", "The quest switches characters automatically at its normal points.", "Use the same movement controls. Link items and fairy return with Link." },
    { "Climbing from water", "Grab a native climbable with a trigger, even while swimming.", "Pull onto land, or release to swim again." },
    { "Settings and rebinding", "A toggles switches, opens sections, or resets sliders to default.", "For bindings: select action, release inputs, press new input, confirm." },
    { "Escaping a grab", "Shake your controllers back and forth to struggle out of a ReDead grab.", "Repeated deliberate shakes help; the original buttons and stick still work." },
    { "Floor-calibrated world scale", "View > World scale: enable, then recenter in your seated or standing play position.", "Tune each form world size. Larger worlds shorten reach. Off restores normal scale." },
    { "Preserving your preferences", "Close the settings menu to save; check for a storage-error message.", "Keep ordinary game saves too. VR settings apply across save files." },
    { "Recovery and diagnostics", "System has the setup guide and a private-safe diagnostic report export.", "Close the game to use Recover VR settings on PC or the Quest recovery app." },
    { "Updates and save states", "Launch checks only notify. Install needs confirmation and may invalidate states.", "Make an ordinary save before updating. Incompatible states are kept, not loaded." },

    { "Hand-mounted HUD", "HUD attachment selects Headset, Left hand or Right hand; Hand HUD size resizes it.", "HUD opacity still applies. Dialogue, pause screens and settings stay separate." },
    { "Bombers' Notebook", "Open the notebook in the pause menu; its page rests on your off hand.", "Touch page arrows or known entries with your other hand. Stick navigation and B to close still work." },
    { "Telescope comfort", "View > Comfort > Stable telescope screen uses the native telescope on a theater screen.", "Switch it off to use the headset-directed telescope view." },
    { "Tracked bodies", "View > Body visibility has separate tracked-body options for each form. Human, Zora and Deku default on.", "Goron and Fierce Deity default off. Off restores previous visibility; Kafei keeps his tracked hands." },
    { "Finding settings", "System > Session and files: Search VR settings. 2Ship has its own search too.", "Persistent Bunny Hood: enable, then press A on the owned hood in the mask menu." },
    { "Combat assistance", "Combat tunes sword/stick and Goron fist hitboxes; Forms tunes Zora fin reach.", "Swords have a small reach aid. Sliders change collision, not models; walls still block." },
};
inline constexpr int ControlTutorialCount = sizeof(ControlTutorial) / sizeof(ControlTutorial[0]);
}
